### ISSUE TITLE
Doesnt work on MacOS Catalina

### ISSUE THREAD

**Issue by alersenkevich** [codebytere/node-mac-permissions#14]
So, i just trying to use ask for camera access

`askForCameraAccess().then((status) => {
  console.log(`Access to Camera is ${status}`);
});`

but i get nodejs crash, so what should i do? 

<img width="552" alt="Снимок экрана 2020-06-14 в 14 30 51" src="https://user-images.githubusercontent.com/29869517/84589928-b030f480-ae4b-11ea-9a0f-7f4e53afe2fe.png">

**Comment by codebytere** [comment]
@alersenkevich i'm going to need more information in order to triage this - that screenshot for example shows me a crash in an app being monitored with nodemon, but it could be a crash _anywhere_ - not necessarily related to my module. If my module crashed, there will be a stacktrace with native code in it - is there? if not, this is likely not the fault of `node-mac-permissions`

**Comment by alersenkevich** [comment]
yeah it is, the problem was in vs code terminal which hasnt ability to request access to media as child process of vs code, i've solved this issue, sorry for issue here, it can be closed

thank you for answer

**Comment by codebytere** [comment]
No worries! glad it's solved :D
