### ISSUE TITLE
Screen capture Access Prompt

### ISSUE THREAD

**Issue by Srini-B** [codebytere/node-mac-permissions#48]
When using askForScreenCaptureAccess(), it doesn't open the respective system preference tab, when tried with askForAccessibilityAccess() it works, using iterm2 and on macOS 12.6. Im asking for both one by one. Tried replacing it by asking accessibility again but it also didn’t open

**Comment by notedit** [comment]
Same here,   @Srini-B any ideas?

**Comment by Srini-B** [comment]
Not an elegant way, but I achieved it using another package
[macos-accessibility-permissions](https://github.com/karaggeorge/macos-accessibility-permissions#readme)
[mac-screen-capture-permissions](https://github.com/karaggeorge/mac-screen-capture-permissions#readme)

**Comment by theogravity** [comment]
I didn't have any success with those recommended packages on the latest electron version `23` and MacOS Ventura.

I was able to do it using the following:

```typescript
import { execSync } from 'child_process';
import { isMacOSVersionGreaterThanOrEqualTo } from 'macos-version';

  if (isMacOSVersionGreaterThanOrEqualTo('10.16')) {
    try {
      execSync('open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"');
    } catch (e) {
      console.log(e)
    }
  }
```

**Comment by codebytere** [comment]
@Srini-B @theogravity does this PR address your issue? https://github.com/codebytere/node-mac-permissions/pull/60

Unfortunately the ergonomics aren't great for forcing the pref pane since it's kind of impossible to check in a clean way whether access has been denied previously or not yet queried, so i ended up adding a bool param to the request method. If that serves both of your needs well i can go ahead and merge it!

**Comment by theogravity** [comment]
Actually it's how one of the other packages does it too. I'm ok with that! Thanks for that PR!
