### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by dmatora** [codebytere/node-mac-permissions#52]
When I add
```
import {getAuthStatus} from "node-mac-permissions";
const status = getAuthStatus('screen');
```
I get 
```
Module not found: Error: Can't resolve 'fs' in '/Users/Shared/Pet/App/app-desktop/node_modules/bindings'
 @ ./node_modules/node-mac-permissions/index.js 1:20-39
```

**Comment by codebytere** [comment]
@dmatora in order to triage this further i need more information. I need to know
 - what operating system you're using
 - what version the OS is on
 - what version of this module you're running

I will also need a code sample I can run to reproduce the issue. The above code snippet does not suffice.

**Comment by dmatora** [comment]
Solution was to use this inside main.ts instead of renderer
